baseURL: "https://hi1993ryan.github.io" 
title: Dr. Jiangrui Liu | 刘江锐 博士
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: pubs/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: CV (EN)
          url: https://hi1993ryan.github.io/md-cv/
          weight: 4

params:
    description: "I am a lecturer of School of Public Policy and Administration at Chongqing University. My research covers various topics including political attitudes and social change, public governance, comparative politics, computational social science, and quantitative methods."
    author: "刘江锐 (Jiangrui Liu)"
    DateFormat: "January 2006"
    defaultTheme: auto
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: "刘江锐 <br><span style='font-size:30px;'>Dr. Jiangrui Liu</span>"
          subtitle: "我是重庆大学公共管理学院的一名老师，目前的研究兴趣（兴趣会流动）：政治态度与社会观念变迁（涉及生命历程研究）、公共治理、比较政治、计算社会科学、量化研究方法。

 <br><br>
I am a faculty member at the School of Public Policy and Administration, Chongqing University. My current research interests, which are dynamic and evolving, span several fields: political attitudes and social change (with a focus on life course studies), public governance, comparative politics, computational social science, and quantitative methods."
          imageUrl: "ca.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Dr. Jiangrui Liu
          buttons:
            - name: Papers
              url: pubs/
            - name: Courses
              url: courses/
            - name: Projects
              url: projects/
            - name: CV (EN)
              url: https://hi1993ryan.github.io/md-cv/
            - name: Tags
              url: tags/
    socialIcons:
        - name: CV
          url: cv/
        - name: Email
          url: mailto:serenity@cqu.edu.cn
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=C_gAro8AAAAJ&hl=en
        - name: GitHub
          url: https://github.com/Hi1993Ryan

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Dr. Jiangrui Liu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2