baseURL: "https://github.com/Hi1993Ryan/Hi1993Ryan.github.io" 
title: Dr. Jiangrui Liu | 刘江锐 博士
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: pubs/
          weight: 1
        - name: Courses
          url: courses/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3 
        #- name: Newsletter
        # url: https://pmichaillat.substack.com
          weight: 4

params:
    description: "I am a lecturer of School of Public Policy and Administration at Chongqing University.\n My research covers various topics.
consequat."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Dr. Jiangrui Liu
          subtitle: "I am a faculty member at the School of Public Policy and Administration, Chongqing University. My current research interests, which are dynamic and evolving, span several fields: political attitudes and social change (with a focus on life course studies), public governance, comparative politics, computational social science, and quantitative methods.
          &nbsp; <br>我是重庆大学公共管理学院的一名老师，目前的研究兴趣（兴趣会流动）涉及：政治态度与社会观念变迁（涉及生命历程研究）、公共治理、比较政治、计算社会科学、量化研究方法。"
          imageUrl: "ava.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Dr. Jiangrui Liu
          buttons:
            - name: Papers
              url: pubs/
            - name: Courses
              url: courses/
            - name: Projects
              url: projects/
            #- name: Newsletter
            #  url: https://pmichaillat.substack.com
            - name: Tags
              url: tags/
            - name: Misc.
              url: misc./
    socialIcons:
        - name: CV
          url: cv/ #cv.pdf
        - name: Email
          url: mailto:ljr17@tsinghua.org.cn
        - name: Location
          url: location/
        - name: Office Hours
          url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=C_gAro8AAAAJ&hl=en
        #- name: YouTube
        #  url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/Hi1993Ryan
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: Twitter
        #  url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Dr. Jiangrui Liu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2